### ISSUE TITLE
Phasing through ceilings using moving platforms

### ISSUE THREAD

**Issue by rhythm-on-github** [Team-Cubey/cubey-issues#8] opened 2020-10-26 20:23 UTC
![image](https://user-images.githubusercontent.com/57626311/97224213-19008400-17d1-11eb-8e4f-9a3136a45a9a.png)
Here's a screenshot that show the bug partway through. The conditions are:
-A moving platform that goes right up to/into/through a ceiling
-Standing around the middle of that moving platform
-staying there and letting the platform push you through the ceiling

Unlike when you get squished from above, this doesn't (necessarily) cause a softlock

**Comment by Hubza** [comment] 2020-10-26 20:31
isn't this the same as #5?

**Comment by rhythm-on-github** [comment] 2020-10-26 20:35
not quite. In #5, you get put inside the moving platform, while here you get put through the non-moving one

**Comment by Hubza** [comment] 2020-10-26 20:37
its still both caused by the same issue though, could you merge these

**Comment by rhythm-on-github** [comment] 2020-10-26 20:39
i'm not sure that it's cause by the same thing though. Are you sure? because the problem with #5 was not that you can get put inside of the moving platform, but just that you can't get out. If you get put inside of a non-moving platform, you can just jump out of it (if there isn't a block above it, at least)

**Comment by rhythm-on-github** [comment] 2020-10-26 20:43
at least, that's how i view it lol

**Comment by Hubza** [comment] 2020-10-26 20:45
they're both caused by the moving platform

**Comment by rhythm-on-github** [comment] 2020-10-26 20:45
true

**Comment by Hubza** [comment] 2020-11-03 18:07
closed in favor of #5

**Closed by Hubza** 2020-11-03 18:07 UTC
